### ISSUE TITLE
GET department/{id}/memberUnits returns duplicate results

### ISSUE THREAD

**Issue by jhoerr** [indiana-university/itpeople-functions-v2#19]
An request to fetch the member units for a given department can return duplicate unit results. I noticed this on the [test server page for UA-VPIT](https://itpeople-test.iu.edu/departments/2547).  

**Request**

`GET https://api.itpeople-test.iu.edu/departments/2547/memberUnits`

**Response**

![image](https://user-images.githubusercontent.com/1151206/112517706-003fce80-8d6f-11eb-97c4-4856b50f78df.png)

**Page view**

![image](https://user-images.githubusercontent.com/1151206/112517059-45173580-8d6e-11eb-85dc-6cd794d910a6.png)

**Comment by jasonfrancis** [comment]
At some point we should rejigger our tests and `TestEntities` to have more complex relationships, without turning over the contract tests apple cart.  But I think that's too much to shoehorn into this issue.
